version: '3.7'
services:
    postgres:
        image: postgres:11.5
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
        ports:
          - "5432:5432"
    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
          - DB_USER=postgres
          - DB_PASS=password
          - DB_HOST=postgres
          - LOGIN_TOKEN=
          - LOGIN_EMAIL=
        depends_on:
            - postgres
        command: src/main.py
        volumes:
            - ./data:/data
